
language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - git clone https://github.com/allisonvacanti/XtalComp.git
install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake
  - cd XtalComp
  - cmake .
  - make
  - sudo make install
  - cd ..
  - pip install .

script:
  - python -m unittest discover tests/